[package]
name = "rachel-riley-countdown-simulator"
version = "0.1.0"
authors = ["Dilip Thomas <dthomas84@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
